// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO0nAGRAl0J9b8pb4nKVL9ClS_ernHEMM',
    appId: '1:329772655927:web:4c41096e8a16900271e6b2',
    messagingSenderId: '329772655927',
    projectId: 'flowerapp-44cc0',
    authDomain: 'flowerapp-44cc0.firebaseapp.com',
    storageBucket: 'flowerapp-44cc0.firebasestorage.app',
    measurementId: 'G-R9JF1MCEKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqJlgJ1u5uKUqqXB0wJ4hnHVWSU0_Y-7I',
    appId: '1:329772655927:android:ad71444d1ab9253671e6b2',
    messagingSenderId: '329772655927',
    projectId: 'flowerapp-44cc0',
    storageBucket: 'flowerapp-44cc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsCe8Fev5ESMLNoPt5PP7w_Mrvto5HiaU',
    appId: '1:329772655927:ios:7226da746f4dbb3a71e6b2',
    messagingSenderId: '329772655927',
    projectId: 'flowerapp-44cc0',
    storageBucket: 'flowerapp-44cc0.firebasestorage.app',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsCe8Fev5ESMLNoPt5PP7w_Mrvto5HiaU',
    appId: '1:329772655927:ios:7226da746f4dbb3a71e6b2',
    messagingSenderId: '329772655927',
    projectId: 'flowerapp-44cc0',
    storageBucket: 'flowerapp-44cc0.firebasestorage.app',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO0nAGRAl0J9b8pb4nKVL9ClS_ernHEMM',
    appId: '1:329772655927:web:5d7091bcc30ed4f271e6b2',
    messagingSenderId: '329772655927',
    projectId: 'flowerapp-44cc0',
    authDomain: 'flowerapp-44cc0.firebaseapp.com',
    storageBucket: 'flowerapp-44cc0.firebasestorage.app',
    measurementId: 'G-PP9NRZV8CZ',
  );
}
